### ISSUE TITLE
Petición de certificado por parte del alumno. Acceso a gestión de modelos.

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/moodle-mod_certifygen#22]
El alumno puede acceder a la gestión de modelos e incluso, le aparece las opciones de editar, borrar, asignar a contexto y crear nuevos modelos.

**Comment by xpazv** [comment]
Pendiente de definir capabilities y valores por defecto para rol de estudiante.

**Comment by elena3ip** [comment]
Corregido para la próxima subida  a develop

**Comment by elena3ip** [comment]
Ya esta subido a develop

**Comment by jmerinogranizo** [comment]
Funciona. ¿Qué capacidad es la que lo controla? ¿mod/certifygen:manage a nivel de sistema?

**Comment by jmerinogranizo** [comment]
Podéis contestarme a la pregunta que os hice.
¿Si es esa la capacidad, qué permite esa capacidad? 
¿Sólo la capacidad de gestionar modelos o más cosas?

**Comment by elena3ip** [comment]
Perdona,  te explico como he organizado las capabilities
- mod/certifygen:manage es a nivel de sistema, por lo que son los gestores los que la van a tener habilitada. Con ella se podrá crear/editar modelos y asociarles contexto. Además, el usuario que se utilice en las llamadas de web service tambien la tendrá que tener.
- mod/certifygen:managecertificates es a nivel de modulol Los profesores la tienen habilitada y por eso pueden emitir y revocar  certificados de alumno
- mod/certifygen:view es a nivel de modulo y la deben de tener tanto alumnos como profesores y gestores para poder acceder a la actividad.
- mod/certifygen:viewmycontextcertificates es a nivel de sistema, para que los profesores puedan emitir certificados 
-mod/certifygen:viewcontextcertificates es a nivel de sistema para que los gestores puedan emitir/revocar certificados en nombre de profesor

Un saludo

**Comment by jmerinogranizo** [comment]
Muchas gracias por tu explicaciones. Me queda bastante más claro. Existen otras tres capacidades, dos las tengo claras:
- mod/certifygen:addinstance
- mod/certifygen:reemitcertificates
pero, ¿qué diferencia exist entre mod/certifygen:canemitotherscertificates y mod/certifygen:canmanagecertificates?
Un saludo y gracias de antemano.

**Comment by elena3ip** [comment]
- mod/certifygen:canmanagecertificates se usa para saber si se puede emitir o revocar certificados de profes que no son uno mismo
- mod/certifygen:canemitotherscertificates para poder emiitr certificados de actividad sin ser el alumno
- mod/certifygen:reemitcertificates: es para re emitir certificados.
- mod/certifygen:addinstance es obligatoria en todos los modulos. sive paa saber si un usuario puede crear este tipo de actividad
-
