### ISSUE TITLE
Actividad certificado del profesor. Falta control de capabilities.

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/moodle-mod_certifygen#34]
Un usuario cualquiera que no esté como profesor en los contextos de los modelos de profesor existente, puede solicitar un certificado de profesor.

**Comment by juacas** [comment]
Faltan los capabilities "mod/certifygen:requestownteacherreport" y "mod/certifygen:requestothersteacherreport"

**Comment by elena3ip** [comment]
Hola, ya estan las comprobaciones en la rama develop

**Comment by jmerinogranizo** [comment]
Como usuario alumno, no consigo ver el enlace. Perfecto.
Como profesor, me salta el siguiente error:
![imagen](https://github.com/user-attachments/assets/2d73031a-0a3f-4559-b22e-1d7129d0372c)
Además faltan las capacidades: "mod/certifygen:requestownteacherreport" y "mod/certifygen:requestothersteacherreport". Si se ha hecho con la capacidad "canemitotherscertificates" no consigo poder solicitar certificados de otros usuarios con el usuario administrador ni con un usuario que tiene un rol creado con todos los permisos excepto "mod/certifygen:viewcontextcertificates".

**Comment by jmerinogranizo** [comment]
Habiéndome explicado Elena algunas de las capacidades y habiendo creado un usuario gestor con todos los permisos incluidos mod/certifygen:viewcontextcertificates, no consigo saber cómo puede solicitar certificados de profesor de otro usuario.
Tampoco me funciona con el usuario administrador.
Por cierto, el usuario administrador o gestor deben estar en algún curso matriculado como profesor para que les aparezca el enlace "Mis Certificados de Unimoodle Certifygen".

**Comment by xpazv** [comment]
Los enlaces de _"Gestion de modelos_" y _"Ver peticiones de certificados de los profesores"_ no los visualiza el rol gestor por defecto.

La razón por la que el gestor, por defecto, no visualiza los enlaces es porque se han implementado dentro un plugin tipo **mod**, 
y Moodle solo carga dichos settings si se tiene activada la capability _"moodle/site:configview"_

Entendemos que habilitarla, puede dar acceso a más configuraciones de las que puede ser aceptable para una figura de Gestor.

Por tanto, valorando una solución que permita habilitar la visualizaciń del acceso, una posible opción puede ser implementar un plugin tipo _admin_tool_ solo con esta configuracion, para poder visualizar los enlaces en roles que no tengan dicha capability.

**Comment by juacas** [comment]
¿Se podrían distribuir los dos plugins en el mismo paquete?

**Comment by elena3ip** [comment]
Si te refieres a paquete a un archivo zip, entonces no, cada plugin un archivo zip diferente.
