### ISSUE TITLE
Tras un error AJAX el interfaz de usuario queda bloqueado.

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-mod_certifygen#43]
Como tenemos mucho diálogo modal con llamadas AJAX, cuando hay un error de cualquier tipo

![image](https://github.com/user-attachments/assets/b1454d05-d580-4734-8118-992c7e14b77a)

El interfaz queda bloqueado con un layer traslúcido.

Comportamiento esperado: Al cerrar el diálogo de error el interfaz debe quedar utilizable.

Bonus track: Obsérvese en la siguiente captura que la Layer traslúcida cubre únicamente una parte de la pantalla y si hay scroll se deja usar la parte inferior de la pantalla.
![image](https://github.com/user-attachments/assets/65878d8a-65b1-421c-a031-212f2d026ae2)

**Comment by xpazv** [comment]
¿Está el modo depuración activado?

El velado y la forma de mostrar el error, en este caso **generalexception** no es algo propio del plugin **mod_certifyGEN** sino del tema de apariencia.

Si el error es critico (_como parece el caso de la imagen_) el interfaz, al hacer uso de llamadas ajax a servicios no puede seguir funcionado.

**Comment by juacas** [comment]
En el tema de serie Boost también aparece el defecto de la capa de bloqueo modal.
![image](https://github.com/user-attachments/assets/f8b48d07-b586-41d0-b3a8-9041608555e1)

**Comment by juacas** [comment]
No se ha vuelto a producir porque el error de AJAX estaba causado por #5 
Cerramos el caso por ahora.
