### ISSUE TITLE
Validación "WEBSERVICE"

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/moodle-mod_certifygen#47]
Si no recuerdo mal de las reuniones realizadas, cuando existía una actividad de certificado con validación de tipo "WEBSERVICE", cuando un usuario lo solicitaba la emisión ya sea certificado de alumno como de profesor, debía aparecerle en estado en progreso e incluyéndole un mensaje que debía solicitarlo vía el sistema externo (administración electrónica o lo que fuera).

Al ejecutar las tareas programadas, se sigue quedando en progreso (como debe) pero no se muestra mensaje.

**Comment by juacas** [comment]
Cierto, los plugins tienen que implementar un método que devuelva un texto para mostrar junto al estado actual de la petición. 
Por ejemplo get_state_description() o similar.

**Comment by elena3ip** [comment]
Está en el código, [rama develop](https://github.com/UNIMOODLE/p31_mod/blob/develop/classes/interfaces/ICertificateValidation.php)

**Comment by jmerinogranizo** [comment]
Ya lo veo Elena, no me había dado cuenta. No sé si el profesor se dará cuenta o no.
En el caso en que lo mantengamos de esa manera, creo que debería ser un texto a incluir en un settings del subplugin y que fuera multiidioma como por ejemplo el settings del core custommenuitems.

**Comment by elena3ip** [comment]
Ya es multiidioma, podeis cambiar el mensaje desde la personalización de idiomas de la plataforma, basta con buscar el texto con clave 'inprogress_msg' del plugin 'certifygenvalidation_webservice'

**Comment by jmerinogranizo** [comment]
Hola Elena, pero un usuario administrador neofito sabría acceder a los lang y luego tenerlo en cuenta en cada actualización.
A ver qué comentan mis compañeros.

**Comment by jmerinogranizo** [comment]
Dicho queda entonces.  Acepto que se cambie en la personalización del idioma en vez de como settings. Espero que no haya gente que no sepa hacerlo.
En cuanto al error, a mí no me da ni como profesor:
![imagen](https://github.com/user-attachments/assets/ab0a9e77-1a9d-4640-823c-c78ea0ed34fc)
Ni como alumno:
![imagen](https://github.com/user-attachments/assets/24507c8c-290c-4637-a7b5-0b5d25db624e)


De todas formas, estoy de acuerdo con Juan Pablo:

**Al menos el solicitante debería ver el mensaje explícitamente en la pantalla.
De todas formas: El tooltip no es adecuado para esta información.**

No sé cómo de complicado será cambiarlo a mensaje explícito, ya que un porcentaje de usuarios no se dará cuenta que tiene que pasar por encima del texto del estado.

**Comment by xpazv** [comment]
Proponemos mostrar un icono de advertencia, junto al estado, que muestre el tooltip con el mensaje explicito.

**Comment by juacas** [comment]
Prefiero que la columna "Estado" tenga un texto completo. No veo la necesidad de usar un componente tipo Botón para un elemento del UI que no desencadena una acción.
Los botones son para las acciones. Las etiquetas para la información al usuario. Además el mensaje devuelto por el método get_status_messages() es de interés directo en todo momento, por lo menos para el solicitante.

Veo cierta utilidad que en las vistas de administrador se reduzca la información de los listados para no saturar el UI, pero no en las vistas de los solicitantes donde toda la información útil debe mostrarse explícitamente.

**Comment by elena3ip** [comment]
Creo que una columna con un texto no es lo mas apropiado la verdad. He añadido junto al estado un icono con el tooltip.
