### ISSUE TITLE
Siendo gestor de categorías y teniendo la capacidad de gestionar modelos, no nos deja hacer la gestión

### ISSUE THREAD

**Issue by tmas0** [UNIMOODLE/moodle-mod_certifygen#53]
Buenas,

Siendo gestor de categorías y teniendo la capacidad mod/certifygen:manage, al ir directamente a la URL, nos arroja el siguiente error:
```
Sorry, but you do not currently have permissions to do that (Manage an unimoodle certifygen certificate).

More information about this error

Debug info:
Error code: nopermissions￼×Dismiss this notification
Stack trace:
line 870 of /lib/accesslib.php: required_capability_exception thrown
line 42 of /mod/certifygen/modelmanager.php: call to require_capability()
```

Proceso seguido:
1. Crear un usuario nuevo en la plataforma.
2. Crear una categoría y generamos un curso vacío dentro de ella.
3. Asociamos una cohorte dónde asignamos al usuario generado y le otorgamos el rol de manager.
4. Al ir a la url salta el error.

En este punto 4, entiendo que debería salir una url pintada en algún lugar, pero al no tener privilegios no se pinta, y por eso vamos directamente por URL.

Cabe notar que esto es un requisito del pliego.

Un saludo

**Comment by elena3ip** [comment]
El rol de manager debe ser a nivel de sistema no a nivel de categoría o cohorte. Entiendo que es por eso por lo que da error.

**Comment by jmerinogranizo** [comment]
A mí, con la url directa sí me deja gestionar modelos pero no consigo que pueda solicitar un certificado de otros profesores el enlace además sólo sale si tienes algún curso pero ni aún así, consigo poder solicitar certificados de otros usuarios.

**Comment by tmas0** [comment]
Buenas @elena3ip,

Pues siendo así, se incumple este requisito del pliego:

> CERT-MOD
> Mecanismo de configuración de modelos de certificado
> Los usuarios con los permisos adecuados tienen acceso a las plantillas y a los modelos accesibles desde su contexto.
>
> Los gestores de categoría podrán definir los modelos de certificado asociadas a una categoría.

Un saludo

**Comment by elena3ip** [comment]
En moodle cuando preguntas si un usuario tiene un permiso concreto hay que especificar un contexto, y se ha definido que el contexto sea sistema. Si el usuario con el que intentas acceder no tiene ese permiso a nivel de sistema no va a poder acceder.

**Comment by tmas0** [comment]
Ok, resuelto.

Un saludo
