### ISSUE TITLE
Falta la validación del comando

### ISSUE THREAD

**Issue by tmas0** [UNIMOODLE/moodle-mod_certifygen#57]
Buenas,

Según el pliego:

1. > Este proceso ha de permitir configurar un comando del sistema operativo del servidor de Moodle pasándole los parámetros que se requiera. Este comando recibirá el documento PDF del certificado por la entrada estándar y se obtendrá el documento modificado de la salida estándar.
2. > Si el plugin no detecta el comando de sistema, no ha de ofrecer este proceso al usuario.

Este segundo punto no se cumple, ya que revisando la interfaz y el código no se valida. Entiendo que esto debería ser como los "path de sistema", dónde se valida de que exista. Luego en código deberá revisar este punto, a fin de no devolver errores.

Un saludo

**Comment by xpazv** [comment]
En revisión.

**Comment by elena3ip** [comment]
En el settings he añadio una validación, si la ruta no existe sale el siguiente mensaje
![image](https://github.com/user-attachments/assets/3753f93d-4d0d-4921-b266-1a25e660d499)

Ya está en develop.

**Comment by tmas0** [comment]
Buenas @elena3ip,

Aunque me parece bien lo implementado, lo estándar en Moodle es marcarlo de forma más común, como por ejemplo en la sección de backups o system paths. Adjunto capturas:

![Selecció_1329](https://github.com/user-attachments/assets/d79b47aa-e254-417f-9b4c-5a52e93cbc99)
![Selecció_1330](https://github.com/user-attachments/assets/58c79ab0-9048-4f3b-bc1b-4cd7573554c7)

Un saludo

**Comment by elena3ip** [comment]
He visto que este elemento es de otro tipo de settings es de otro tipo e incluye la validación del path en cuestión. Lo cambio. Gracias por la aportación.

**Comment by elena3ip** [comment]
Ya está el cambio en develop

**Comment by tmas0** [comment]
Buenas @elena3ip,

El primer field ya está bien, pero los dos otros no se validan.

![Selecció_1331](https://github.com/user-attachments/assets/420013b3-e6a0-4565-a904-6180998b02f8)

Un saludo

**Comment by elena3ip** [comment]
Modificado! ya está el cambio en develop

**Comment by jmerinogranizo** [comment]
A mi me funcionan originalfilespath y validatedfilespath, pero aún cuando el settings path sea válido simpre me sale la aspa roja, aunque no me sale el texto de debajo de Path no válido.

**Comment by jmerinogranizo** [comment]
A mi me funcionan originalfilespath y validatedfilespath, pero aún cuando el settings path sea válido simpre me sale la aspa roja, aunque no me sale el texto de debajo de Path no válido.
He purgado las cachés pero nada.
Un saludo.

**Comment by elena3ip** [comment]
A mi me sale bien, nada mas acceder a la página de configuración aparece
![image](https://github.com/user-attachments/assets/800f583c-5cd8-4d84-a89f-c5d92a1998a3)

Cambio una de las rutas y después de darle a guardar veo:
![image](https://github.com/user-attachments/assets/113c321e-102d-4a2a-a59c-202da62442ee)

**Comment by jmerinogranizo** [comment]
Perdona Elena, pero me faltaban los permisos de ejecución al sh.
Error grave por mi parte.
Cierro el issue.
