### ISSUE TITLE
Tabla certifygen_validations. Necesidad de campo modelid

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/moodle-mod_certifygen#62]
En vista que existe un campo "certifygenid" en esa tabla en donde se especifica también el modelo y que una vez que se emite un certificado en ese modelo, con los requisitos que se acordó en alguna reunión, el profesor no puede cambiar el modelo en una actividad de alumno, no veo la necesidad del campo "modelid" en la tabla certifygen_validations.

**Comment by elena3ip** [comment]
En esta tabla se registran tanto las peticiones de alumnos (asociadas a un certifygenid) como las de profesor (que no están asociadas a un certifygenid) pero que sí tienen que estar relacionadas con un modelid y por eso es necesario la existencia de esa columna, ya que no existe otra tabla que relacione la petición de un profesor con el modelo.
