### ISSUE TITLE
Bug en refresco tras emitir Certificado

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-mod_certifygen#66]
Cuando un estudiante pide emitir su certificado, el diálogo modal se cierra pero no se produce la recarga de la página hasta después de casi un minuto. Durante ese intervalo la tabla se mantiene sin actualizar, con el estado "no iniciado" y con el botón de Emitir todavía activo.

¿Cuál es el comportamiento diseñado para este refresco?

PD: Este diálogo modal está causando complicaciones en varias areas del interfaz. Hubiera sido mejor implementar el clásico formulario con página dedicada.

**Comment by elena3ip** [comment]
Era un problema de css, el loading se quedaba por encima de la tabla. Ya está la corrección en develop
