### ISSUE TITLE
Fallo en informe de profesor si no hay estudiantes en un curso

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-mod_certifygen#69]
El informe de profesor falla con el error "no students in course" 
![image](https://github.com/user-attachments/assets/07a49b3c-0c62-4d8f-88ed-08c36cadaab0)

y la solicitud se queda en un estado [[status_9]]

![image](https://github.com/user-attachments/assets/84558f9a-deb4-4408-a126-03bcf18a3da9)

Al Borrar la petición aparece el error:
![image](https://github.com/user-attachments/assets/c3575f88-d5ec-4925-98ba-dd0e84a3c66e)

Y no se borra la petición por lo que no se puede pedir una nueva.

Comportamiento esperado:
- La intención de borrado del administrador debe llevarse a cabo tras una confirmación.
- El mensaje de error debe aportar indicaciones para tratar el problema.
- En caso de ausencia de estudiantes en un grupo debe poder ejecutarse el informe. No se entiende cual es la lógica del comportamiento actual.

**Comment by juacas** [comment]
Otro aspecto de esta pantalla.

El botón de "Crear petición" no debe desaparecer tras hacer la petición. Sobre todo si la opción de emisión reiterativa está activa en el modelo.

**Comment by elena3ip** [comment]
Resumo los puntos a tratar:
- en el buscador no deben aparecer cursos sin alumnos ya que es necesario para poder crear el informe (Para sacar los datos en muchas operaciones se divide entre el numero de estudiantes, por lo que no se puede dividir entre 0) (Se sube la corrección en breve a develop)
- Poder eliminar una petición (Lo que sucede es que para eliminar la petición no tenia en cuenta el estado y siempre se intentaba primero eliminar desde el método de validación, en este caso no existía tal petición por lo que daba error.) (Se sube la corrección en breves a develop )
- La desaparición del botón de crear petición
- Confirmación del borrado

**Comment by tmas0** [comment]
Buenas @elena3ip,

He intentado generar un certificado usando el idioma Español, pero el certificado se emite en Inglés. Lo comento aquí por no generar otro ticket cuando creo que esto está relacionado con lo que se habla en esta incidencia.
Si no es así, obro otro, sin problema.

Un saludo

**Comment by juacas** [comment]
En los casos en que el denominador sea el número de estudiantes y éste sea 0, también el numerador debería ser 0, el indicador debe tomar el valor 0.

El objetivo de dividir por el número de estudiantes es obtener una media normalizada.
Añadir simplemente la  comprobación: $numstudents==0?0:$valor/$numstudents como salvaguarda.

Es importante que en el caso de que entre la petición del informe de un curso sin estudiantes (por ejemplo mediante WS) se obtenga un resultado del modelo.

Un saludo.

**Comment by elena3ip** [comment]
Ya está el cambio en develop

**Comment by tmas0** [comment]
La parte que me corresponde, está comprobada.

**Comment by tmas0** [comment]
También he comprobado la parte que comenta @juacas, viendo que ya va bien.
