### ISSUE TITLE
Backup no implementado.

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-mod_certifygen#71]
No existe la funcionalidad Backup/Restore fundamental para la operativa básica.
Esta funcionalidad es mínimo factor múltiplo de todos los desarrollos.
Creo que también provoca que no exista la función "Duplicar".

**Comment by xpazv** [comment]
Es necesario definir los siguientes aspectos:

- ¿En qué términos se define el backup y restore para esta actividad de curso? ¿Solo datos o datos y ficheros? ¿modelos?
- ¿De qué manera se deben conservar todos los ficheros de certificados ya emitidos, que dependan de subplugins de almacenamiento externos (One Drive, CSV)?
- ¿Cómo se debe tratar el enfoque de los modelos usados en actividades de este tipo para procesos de restore y backup? 
- ¿Se deben incluir todos los modelos o solo los modelos usados en esa actividad? 
- ¿Qué ocurre si un modelo está asignado a un contexto, este pasa a formar parte del backup y en el restore, ese contexto no existe?
- Indicar que los certificados de profesor no pueden formar parte del backup ni restore, puesto que no están asociados a ninguna actividad.

**Comment by juacas** [comment]
Bajo mi punto de vista, lo más importante del proceso de Backup/Restore es asegurar que:
1) La operación "duplicar" funciona dentro de un curso.
2) La operación "Importar" funciona entre cursos de la misma plataforma.
3) La operación "Backup/Restore" funciona entre diferentes clones de la misma plataforma (por ejemplo, plataforma de año anterior congelada) como son los casos contemplados en el proyecto CourseTransfer.

Partes del modelo que no pueden ser restauradas por un profesor:
1) Plantillas y modelos del gestor: Supongo que estas partes deben existir previamente a la restauración y hay que manejar el caso en que no existan. ¿Cómo lo hace mod_coursecertificate? ¿Usamos un identificador "inmutable" como el campo que introdujimos como idnumber del modelo? Al tener un caracter "institucional" y no ser un id técnico incremental puede ser más reproducible y generable a mano por los gestores.
2) Ficheros locales: Únicamente serían incluibles en un backup los ficheros almacenados en el repositorio local. el resto se almacenarían como referencias a los repositorios externos. Por supuesto, se copian o restauran solamente si se selecciona y se tiene el permiso de "copiar datos de usuario".

Para los modelos y plantillas, debe poder copiar/restaurar únicamente un usuario con permisos para ello (el mismo que la creación de modelos y plantillas). A la hora de incluir uno o todos los modelos/plantillas no tengo claro qué conviene más, porque el caso de uso más razonable no es incluirlo en el backup de un curso sino hacer un backup/restoure a nivel de plataforma de modelos y plantillas.

Creo que sería más útil y más fácil de implementar añadir una opción a settings para exportar/importar en json modelos y plantilllas y luego hacer el mapeo pro idnumber del modelo en las copias de seguridad de cursos.

En caso de no existir, yo lo manejaría:

1) Mostrar un Warning escandaloso indicando que "no se encuentra el modelo de certificación "idnumber". Contacte con su administrador".
2) Marcar la instancia de mod_certifigen con el idnumber del modelo además del id secuencial.

**Comment by xpazv** [comment]
Moodle solo maneja los siguientes tipos de backups, desde dentro del curso

![moodle_backup_types](https://github.com/user-attachments/assets/c1b0b54d-d6c6-4e4e-83bd-1c785ecdadda)

Por tanto, todos aquellos elementos a nivel de sistema, a priori, no son considerados como parte del backup.

Existe la opción de importar y exportar configuración, que puede ser una solución viable para los modelos.

**Comment by juacas** [comment]
Pues entonces es evidente que el Backup/Restore a nivel de activity debe incluir el idnumber del modelo y controlar la posibilidad de que puede no existir en el momento de la restauración.
Yo lo resolvería así:
1) Se restaura una actividad que tiene un "certifygen.modelidnumber" (campo que ahora aún no existe).
2) Si no existe el "certifygen_model.idnumber" al restaurar, almaceno un NULL en el campo del "certifygen.modelid".
3) Si al entrar en view.php se encuentra que "certifygen.modelid == NULL" y  "certifygen_model_modeloid == certifygen.modelidnumber",  existe (porque lo ha creado un gestor después de hacer la restauración), entonces se escribe el "certifygen.modelid" correcto y todo sigue igual que hasta ahora.
4) La actividad no puede usarse si el "certifygen.modelid" es NULL. Hagamos que view.php muestre únicamente un mensaje indicando que no existe ningún modelo seleccionado, si hay un valor en "certifygen.modelidnumber" con identificador "idnumber" se incluye en el mensaje para que se contacte con el administrador.


¿Puede ser una buena implementación?

**Comment by jmerinogranizo** [comment]
Lo primero perdonad la tardanza en contestar. Dicho esto, revisando todo lo escrito hasta ahora, os comento mi opinión:

- Estoy de acuerdo con que debe permitirse importar, backup/restore y duplicar una actividad de certificado de alumno como comenta Juan Pablo.
- Exportación/importación de modelos por parte del gestor de modelos o administración. Tener en cuenta que si el contexto no existe, se debe marcar como contexto NULL para que pueda el gestor asignarle el nuevo contexto.
- Un profesor no puede restaurar modelos y plantillas por lo que habéis comentado de que son elementos del sistema y no propios del backup.
- Me parece bien lo que comenta Juan Pablo de certifygen.modelidnumber para identificar de forma exclusiva un modelo para que se puedan importar en entornos diferentes. 
- En la restauración estoy de acuerdo en lineas generales con lo que comenta Juan Pablo, pero además si el modelo que está asociado a la actividad existe (identificado por certifygen.modelidnumber) hay que comprobar que cumpla que se puede aplicar en el contexto en donde se restauraría esa actividad. Si no, dejaría  un NULL  en certifygen.modelid y mostraría un warning para que se pusiera en contacto con el administrador.
-  Tengo mis dudas sobre la necesidad de restaurar los datos de usuario de esas actividades. Hay que guardar la información en la copia pero en la restauración, no le veo mucho sentido qerer  tener una nueva actividad con los certificados ya emitidos. Al menos desde el rol del profesor. Tal vez desde el rol del administrador pero no estoy seguro.

Un saludo.

**Comment by xpazv** [comment]
Por coherencia con el enfoque y la implementación actual se descarta la creación de una actividad vacia si el modelo no existe, pues es obligatorio que toda actividad tenga un modelo asociado, y contemplar actividades sin modelo genera incoherencias con los requerimientos implementados.

**Comment by juacas** [comment]
Creo que eso nos va a generar un problema operativo serio en caso de restauraciones masivas automatizadas.
Si descartamos esto habría que ser capaces de abortar completamente la restauración antes de empezar. ¿Es posible?

Escenario 1:
- Usamos Course Transfer para traspasar una categoría con 100 cursos que todos tienen un proceso de certificación.
- En la plataforma destino hay un error en el ID del modelo o éste no existe.

¿Qué ocurre aquí?
1) Se restauran los cursos completamente omitiendo las actividades mod_certifygen problemáticas. ¿El registro de restauración mostraría este defecto?
2) Se abortan las restauraciones. En este caso la operación se detecta  y puede corregirse el problema si el mensaje es suficientemente claro: debe indicar que ID de modelo está buscando.

Escenario 2:

- Restauración de copia de seguridad en un contexto histórico o congelado.
- El objetivo es mantener las referencias y permitir únicamente consultar. No se permiten emitir nuevos certificados.

¿En este caso podríamos usar un modelo "fake" con subplugins nulos o desactivados? ¿Cuál de los dos resultados anteriores se producirán: 1 o 2?

Por cierto, ¿Qué pasa si el administrdor desactiva un subplugin que está enlazado a modelos en uso? ¿Se comprueba en los puntos adecuados que los subplugins pueden desactivarse a nivel de plataforma?

**Comment by xpazv** [comment]
Se puede abortar la restauración de la actividad, si alguno de los pasos establecidos en la rutina de restore no se cumplen. Y por tanto, la actividad no se restaura.

> ¿En este caso podríamos usar un modelo "fake" con subplugins nulos o desactivados? ¿Cuál de los dos resultados anteriores se producirán: 1 o 2?

Siempre que exista un modelo, y tenga la misma denonimación que la que consta en el fichero de backup, la restauración se realiza por completo.

En el caso del **escenario 1**, si no existe el modelo con la denominación esperada, el resultado debe ser el punto 1

En el caso del **escenario 2**, en ese contexto histórico o congelado debe existir el modelo con la denominación esperada por la información almacenada en los ficheros de backup, y además el modelo debe estar configurado en las mismas condiciones.

> Por cierto, ¿Qué pasa si el administrdor desactiva un subplugin que está enlazado a modelos en uso? ¿Se comprueba en los puntos adecuados que los subplugins pueden desactivarse a nivel de plataforma?

En el paso de _restore_ relativo al modelo, se comprueban que las condiciones del modelo encontrado, en relación a la configuración, tal y como indicábamos anteriormente.

"_Comprobar que las condiciones del modelo existente coinciden con el que se usó._"

**Comment by juacas** [comment]
Me refería a abortar la restauración completa de TODA la restauración no solo de la actividad, por ejemplo la de un curso completo. ¿Podría abortarse la restauración en las fases de verificación.
El objetivo es no dejar una restauración parcial sin que el administrador o usuario lo sepa. En las operaciones manuales se pueden ver warnings, pero en operaciones por lotes pueden pasar desapercibidas.

**Comment by juacas** [comment]
Sobre 

> En el paso de restore relativo al modelo, se comprueban que las condiciones del modelo encontrado, en relación a la configuración, tal y como indicábamos anteriormente.
> 
> "Comprobar que las condiciones del modelo existente coinciden con el que se usó."

No me refiero al proceso de restauración sino al funcionamiento general de todo el plugin. Me doy cuenta que es un off-topic, perdón por ello.

**Comment by jmerinogranizo** [comment]
> Me refería a abortar la restauración completa de TODA la restauración no solo de la actividad, por ejemplo la de un curso completo. ¿Podría abortarse la restauración en las fases de verificación. El objetivo es no dejar una restauración parcial sin que el administrador o usuario lo sepa. En las operaciones manuales se pueden ver warnings, pero en operaciones por lotes pueden pasar desapercibidas.

No conozco en profundidad el plugin "course transfer", ¿pero ahí no hay la posibilidad de trazar el log de la restauración? ¿Y en caso de que sea afirmativo, se incluirían los warning?

**Comment by juacas** [comment]
El problema es qué hacer en procesos automatizados masivos cuando hay una discrepancia en el modelo.

Si en la validación del fichero de backup se pudiera abortar la operación completa, sería la opción que yo preferiría. Pero no sé si el API de Moodle Backup lo permite.

**Comment by elena3ip** [comment]
Hola,  ya he subido a develop la implementación del backup. Hay que tener varias cosas en cuenta...

- 1.- He tenido que añadir una nueva tabla a la base de datos, por lo que os recomiendo desinstalar y volver a instalar el plugin. Está implementado el upgrade, pero las actividades que ya tengáis creadas no creo que funcionen.

- 2.- Si no existe el modelo lanza un error para impedir la restauración de la actividad.
En el caso en que se restaure la actividad en el mismo moodle que se hizo el backup, el certificado inicial(correspondiente al tool_certificate) va a ser comun para ambos certificados, ya que no se pueden tener dos códigos iguales en la tabla tool_certificate_issues, pero el certificado correspondiente a certifygen si que se duplica en el moodledata. Por las pruebas que he realizado de repositorio onedrive, csv y local no parece que genere errores.

-2.- Si el curso destino no corresponde al contexto del modelo, también lanza error y se impide la restauración de la actividad.

**Comment by jmerinogranizo** [comment]
> * 2.- Si no existe el modelo lanza un error para impedir la restauración de la actividad.

Elena,¿y sí se restauran las demás actividades y recursos del backup o no se restaura nada?

**Comment by jmerinogranizo** [comment]
> Hola, ya he subido a develop la implementación del backup. Hay que tener varias cosas en cuenta...
> 
>     * 1.- He tenido que añadir una nueva tabla a la base de datos, por lo que os recomiendo desinstalar y volver a instalar el plugin. Está implementado el upgrade, pero las actividades que ya tengáis creadas no creo que funcionen.
> 
>     * 2.- Si no existe el modelo lanza un error para impedir la restauración de la actividad.
>       En el caso en que se restaure la actividad en el mismo moodle que se hizo el backup, el certificado inicial(correspondiente al tool_certificate) va a ser comun para ambos certificados, ya que no se pueden tener dos códigos iguales en la tabla tool_certificate_issues, pero el certificado correspondiente a certifygen si que se duplica en el moodledata. Por las pruebas que he realizado de repositorio onedrive, csv y local no parece que genere errores.
> 
> 
> -2.- Si el curso destino no corresponde al contexto del modelo, también lanza error y se impide la restauración de la actividad.

Elena, con esta última versión, al eliminar el campo modelid de la tabla certifygen, falla al menos el servicio web get_id_instance_certificate ya que se intenta coger el modelid de esa tabla que ya no existe. Relacionado con #45

**Comment by jmerinogranizo** [comment]
> Hola, ya he subido a develop la implementación del backup. Hay que tener varias cosas en cuenta...
> 
>     * 1.- He tenido que añadir una nueva tabla a la base de datos, por lo que os recomiendo desinstalar y volver a instalar el plugin. Está implementado el upgrade, pero las actividades que ya tengáis creadas no creo que funcionen.
> 
>     * 2.- Si no existe el modelo lanza un error para impedir la restauración de la actividad.
>       En el caso en que se restaure la actividad en el mismo moodle que se hizo el backup, el certificado inicial(correspondiente al tool_certificate) va a ser comun para ambos certificados, ya que no se pueden tener dos códigos iguales en la tabla tool_certificate_issues, pero el certificado correspondiente a certifygen si que se duplica en el moodledata. Por las pruebas que he realizado de repositorio onedrive, csv y local no parece que genere errores.
> 
> 
> -2.- Si el curso destino no corresponde al contexto del modelo, también lanza error y se impide la restauración de la actividad.

Probando esta nueva versión he encontrado los siguientes errores en base a las pruebas realizadas:

- Si no existe el modelo lanza un error para impedir la restauración de la actividad. Eso está bien pero el texto debería indicar el nombre de la actividad que ha fallado y el nombre del modelo (name e idnumber) para que pueda contactar con el administrador del entorno destino. No se restaura ninguna actividad del backup.
-      ¿Se podría hacer una verificación previa antes de este tipo de actividades antes de realizar el backup? Lo digo por lo planteado Juan Pablo.
- 
- Para saber si el modelo del backup existe en el Moodle destino se debe buscar y comparar por el campo certifygen_model.idnumber y no por el campo certifygen_model.name. El campo idnumber será como el identificador del modelo.
- Está controlado que el contexto donde se va a restaurar la actividad se encuentra dentro de los contextos del modelo (al menos se ha comprobado con modelo asociado a categoría).
- Si existen los modelos de las actividades y éstas están dentro de los contextos de los diferentes modelos se restaura todo. Eso sí, se asocian las actividades nuevas con el model.id del backup cuando debería ser con el model.id del entorno destino que esté asociado con el model.idnumber del backup. En detalle, debería asociarse en la tabla certifygen_cmodels, la nueva actividad certifygen con el model.id asociado al idnumber del backup. Esto provoca que no se puedan acceder a las actividades cuyo model.id del backup no exista en el entorno nuevo.
-

**Comment by elena3ip** [comment]
> > * 2.- Si no existe el modelo lanza un error para impedir la restauración de la actividad.
> 
> Elena,¿y sí se restauran las demás actividades y recursos del backup o no se restaura nada?

Entiendo que te refieres a una restauración de curso. Por lo que he probado no se crea el curso restaurado ya que se ha lanzado una excepción.
En el caso de restauración solo de actividad acabo de corregir que no se cree ninguna referencia a la actividad nueva.

**Comment by elena3ip** [comment]
> > Hola, ya he subido a develop la implementación del backup. Hay que tener varias cosas en cuenta...
> > ```
> > * 1.- He tenido que añadir una nueva tabla a la base de datos, por lo que os recomiendo desinstalar y volver a instalar el plugin. Está implementado el upgrade, pero las actividades que ya tengáis creadas no creo que funcionen.
> > 
> > * 2.- Si no existe el modelo lanza un error para impedir la restauración de la actividad.
> >   En el caso en que se restaure la actividad en el mismo moodle que se hizo el backup, el certificado inicial(correspondiente al tool_certificate) va a ser comun para ambos certificados, ya que no se pueden tener dos códigos iguales en la tabla tool_certificate_issues, pero el certificado correspondiente a certifygen si que se duplica en el moodledata. Por las pruebas que he realizado de repositorio onedrive, csv y local no parece que genere errores.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > -2.- Si el curso destino no corresponde al contexto del modelo, también lanza error y se impide la restauración de la actividad.
> 
> Elena, con esta última versión, al eliminar el campo modelid de la tabla certifygen, falla al menos el servicio web get_id_instance_certificate ya que se intenta coger el modelid de esa tabla que ya no existe. Relacionado con #45

Cierto! y se me olvidó pasar los tests! ya está la corrección subida a develop

**Comment by elena3ip** [comment]
> Probando esta nueva versión he encontrado los siguientes errores en base a las pruebas realizadas:
> 
> * Si no existe el modelo lanza un error para impedir la restauración de la actividad. **Eso está bien pero el texto debería indicar el nombre de la actividad que ha fallado y el nombre del modelo (name e idnumber) para que pueda contactar con el administrador del entorno destino**. 
**CAMBIO REALIZADO**
> * **No se restaura ninguna actividad del backup en caso de error**. Esto es correcto. Pero, **¿se podría hacer una verificación previa antes de este tipo de actividades antes de realizar el backup?** Lo digo por lo planteado Juan Pablo.
Pues la verdad es que no. El proceso de backup/restore va por jerarquía de tablas por tanto por cada elemento que hay en la jerarquía solo accedo a los datos de ese paso. Por tanto, las comprobaciones que puedo hacer son en cada uno de los pasos que hay en el restore. Lo que finalmente he hecho, es que si se lanza un error durante el proceso, elimino de la base de datos los registros relacionados con la actividad. De tal manera que no quede creada a medias.

> * **Para saber si el modelo del backup existe en el Moodle destino se debe buscar y comparar por el campo certifygen_model.idnumber y no por el campo certifygen_model.name**. El campo idnumber será como el identificador del modelo.
**CAMBIO REALIZADO**
> * Está controlado que el contexto donde se va a restaurar la actividad se encuentra dentro de los contextos del modelo (al menos se ha comprobado con modelo asociado a categoría).
> * Si existen los modelos de las actividades y éstas están dentro de los contextos de los diferentes modelos se restaura todo. Eso sí, **existe un problema y es que se asocian las actividades nuevas con el model.id del backup cuando debería ser con el model.id del entorno destino que esté asociado con el model.idnumber del backup**. En detalle, debería asociarse en la tabla certifygen_cmodels, la nueva actividad certifygen con el model.id asociado al idnumber del backup. Esto provoca que no se puedan acceder a las actividades cuyo model.id del backup no exista en el entorno nuevo.
** NO REPRODUZCO ESTE PROBLEMA.... A MI SI SE ME ASOCIA AL NUEVO MODELID. **
La parte del código que lo hace es esta
![image](https://github.com/user-attachments/assets/aa406fcb-fdd3-4361-8b87-65210a1a938d)
Los pasos que he dado son:
- creo un modelo con idnumber XXX
- creo actividad asociado a ese modelo
- hago un backup de la actividad
- edito el modelo y le cambio el idnumber
- creo un modelo nuevo con el idnumber XXX
- restauro la actividad en un curso que cumpla con el contexto del modelo nuevo

Si es otra casuística la que has probado, dímela a ver si consigo reproducirlo por favor.

**Comment by jmerinogranizo** [comment]
> > Hola, ya he subido a develop la implementación del backup. Hay que tener varias cosas en cuenta...
> > ```
> > * 1.- He tenido que añadir una nueva tabla a la base de datos, por lo que os recomiendo desinstalar y volver a instalar el plugin. Está implementado el upgrade, pero las actividades que ya tengáis creadas no creo que funcionen.
> > 
> > * 2.- Si no existe el modelo lanza un error para impedir la restauración de la actividad.
> >   En el caso en que se restaure la actividad en el mismo moodle que se hizo el backup, el certificado inicial(correspondiente al tool_certificate) va a ser comun para ambos certificados, ya que no se pueden tener dos códigos iguales en la tabla tool_certificate_issues, pero el certificado correspondiente a certifygen si que se duplica en el moodledata. Por las pruebas que he realizado de repositorio onedrive, csv y local no parece que genere errores.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > -2.- Si el curso destino no corresponde al contexto del modelo, también lanza error y se impide la restauración de la actividad.
> 
> Elena, con esta última versión, al eliminar el campo modelid de la tabla certifygen, falla al menos el servicio web get_id_instance_certificate ya que se intenta coger el modelid de esa tabla que ya no existe. Relacionado con #45 

CORREGIDO Y COMPROBADO.

**Comment by jmerinogranizo** [comment]
> > > * 2.- Si no existe el modelo lanza un error para impedir la restauración de la actividad.
> > 
> > 
> > Elena,¿y sí se restauran las demás actividades y recursos del backup o no se restaura nada?
> 
> Entiendo que te refieres a una restauración de curso. Por lo que he probado no se crea el curso restaurado ya que se ha lanzado una excepción. En el caso de restauración solo de actividad acabo de corregir que no se cree ninguna referencia a la actividad nueva.




> > > * 2.- Si no existe el modelo lanza un error para impedir la restauración de la actividad.
> > 
> > 
> > Elena,¿y sí se restauran las demás actividades y recursos del backup o no se restaura nada?
> 
> Entiendo que te refieres a una restauración de curso. Por lo que he probado no se crea el curso restaurado ya que se ha lanzado una excepción. En el caso de restauración solo de actividad acabo de corregir que no se cree ninguna referencia a la actividad nueva.

Elena ESTO ES MUY CURIOSO. Cuando se realiza una restauración y falla, en nuestro caso, por una actividad certifygen que no tenía ese modelo en el curso a restaurar, resulta que las actividades anteriores en el backup del curso se generan (aunque no se ven en el curso) y no hay rollback. 
Te cuento mi caso:  

- Yo tenía EN EL BACKUP foros, otras actividades certifygen y una tarea antes de la actividad que da fallo. Después de esa actividad tenía otra tarea y otro certificado.
- Pues bien, se han generado registros de las actividades anteriores para las actividadesanteriores del backup, creando registros en mdl_course_modules así como en mdl_certifygen, mdl_certifygen_cmodels, mdl_assign y otras relativas a mdl_assign, mdl_forum y otras relativas a mdl_forum. Para la actividad que falló, se ha generado únicamente registro en mdl_course_modules pero no en ninguna de las tablas de mdl_certifygen.
- Para las posteriores, no se han creado ningún registro en ninguna tabla. BIEN.
- No sé si es el comportamiento normal de las restauraciones infructuosos de Moodle o es propio de nuestro fallo en certifygen.
- El caso es que no se visualizan esas actividades en el curso aunque están en la base de datos.
- LO MÁS RARO ES QUE DESPUÉS DE PASADO UN TIEMPO, NO SÉ SI POR QUE SE HA EJECUTADO EL CRON O JUSTO SE HA RESTAURADO UNA COPIA BUENA CON UNA ACTIVIDAD CERTIFYGEN HAN APARECIDO ESAS ACTIVIDADES ANTERIORES.
- Luego si las borras las actividades y ejecutas el cron, borras la información de las tablas correspondientes.

**Comment by jmerinogranizo** [comment]
> > Probando esta nueva versión he encontrado los siguientes errores en base a las pruebas realizadas:
> > 
> > * Si no existe el modelo lanza un error para impedir la restauración de la actividad. **Eso está bien pero el texto debería indicar el nombre de la actividad que ha fallado y el nombre del modelo (name e idnumber) para que pueda contactar con el administrador del entorno destino**.
> >   **CAMBIO REALIZADO**
**COMPROBADO**
> > * **No se restaura ninguna actividad del backup en caso de error**. Esto es correcto. Pero, **¿se podría hacer una verificación previa antes de este tipo de actividades antes de realizar el backup?** Lo digo por lo planteado Juan Pablo.
**COMENTADO LO QUE SUCEDE EN UN COMENTARIO ANTERIOR**
> >   Pues la verdad es que no. El proceso de backup/restore va por jerarquía de tablas por tanto por cada elemento que hay en la jerarquía solo accedo a los datos de ese paso. Por tanto, las comprobaciones que puedo hacer son en cada uno de los pasos que hay en el restore. Lo que finalmente he hecho, es que si se lanza un error durante el proceso, elimino de la base de datos los registros relacionados con la actividad. De tal manera que no quede creada a medias.
**COMENTADO LO QUE SUCEDE EN UN COMENTARIO ANTERIOR**
> 
> > * **Para saber si el modelo del backup existe en el Moodle destino se debe buscar y comparar por el campo certifygen_model.idnumber y no por el campo certifygen_model.name**. El campo idnumber será como el identificador del modelo.
> >   **CAMBIO REALIZADO**
**COMPROBADO**
> > * Está controlado que el contexto donde se va a restaurar la actividad se encuentra dentro de los contextos del modelo (al menos se ha comprobado con modelo asociado a categoría).
> > * Si existen los modelos de las actividades y éstas están dentro de los contextos de los diferentes modelos se restaura todo. Eso sí, **existe un problema y es que se asocian las actividades nuevas con el model.id del backup cuando debería ser con el model.id del entorno destino que esté asociado con el model.idnumber del backup**. En detalle, debería asociarse en la tabla certifygen_cmodels, la nueva actividad certifygen con el model.id asociado al idnumber del backup. Esto provoca que no se puedan acceder a las actividades cuyo model.id del backup no exista en el entorno nuevo.
> >   ** NO REPRODUZCO ESTE PROBLEMA.... A MI SI SE ME ASOCIA AL NUEVO MODELID. **
> >   La parte del código que lo hace es esta
> >   ![image](https://private-user-images.githubusercontent.com/118371011/379765357-aa406fcb-fdd3-4361-8b87-65210a1a938d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTc4MzUsIm5iZiI6MTcyOTg1NzUzNSwicGF0aCI6Ii8xMTgzNzEwMTEvMzc5NzY1MzU3LWFhNDA2ZmNiLWZkZDMtNDM2MS04Yjg3LTY1MjEwYTFhOTM4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMTU4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzUyNjA3YzFhOWMxNWRlNWU3MGNlMTRhZDU0MTU5YWMyYTc1YmFhOGMwZWIxYTdjY2VjZDU0NmFmYzNiODU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Io02hQaMO_t3OWafJwby6Mm4TV_edmW_gWkJAx361tY)
> >   Los pasos que he dado son:
> 
>     * creo un modelo con idnumber XXX
> 
>     * creo actividad asociado a ese modelo
> 
>     * hago un backup de la actividad
> 
>     * edito el modelo y le cambio el idnumber
> 
>     * creo un modelo nuevo con el idnumber XXX
> 
>     * restauro la actividad en un curso que cumpla con el contexto del modelo nuevo
> 
> 
> Si es otra casuística la que has probado, dímela a ver si consigo reproducirlo por favor.
**GRACIAS ELENA, A MI AHORA SI ME ASOCIA EL MODELID NUEVO**

**Comment by jmerinogranizo** [comment]
Perdona mi desconocimiento Elena. Te escribo sobre el mismo mensaje tuyo.
> Lo que comentas de que no aparecen las actividades y luego si, eso es por el cron.

¿Entiendo por tanto que independientemente de si se tienen actividades certifygen o NO, el cron de Moodle restaura las que se habían restaurado antes de producirse la excepción? Por favor, confírmamelo. ¿Se podría hacer que el cron NO restaurase las actividades anteriores a la excepción?, es decir que no se restaurase ninguna actividad.

 
> Por otra parte, para que aparezca un mensaje del motivo por el cual la actividad no se ha restaurado es necesario lanzar una excepción y por tanto implica que no se va a restaurar el curso completo. Si no se quiere impactar en el proceso de restauración y simplemente dejar registrado en base de datos el error, entonces es posible no lanzar la excepción y se restaurará todas las actividades que sean posibles. El problema de esta ultima opción es que el usuario final no va a ser consciente de que la actividad ha fallado y el por qué salvo que pueda revisar los logs de errores.

Desde luego hay que mostrar un mensaje al usuario de que la restauración ha fallado y si implica que no se restaura el curso, pues no se restaura. Pero por otro lado, si se está lanzando la excepción, al menos con el cron se restauran todas las actividades anteriores a la excepción, ¿no?. LO PRIORITARIO,  es que el usuario o el sistema tipo course_transfer se entere de que ha fallado la restauración. Si no se restauran actividades, no se restauran.
> 
> Dado que el proceso de restauración es propio de la actividad, hay que decidir le flujo que se desea. No es cuestión de que es lo normal, ya que la complejidad de esta actividad no la tienen otras de Moodle.

Creo que debe saltar excepción y no permitir restaurar el curso.

Por favor, @juacas y @peptonic, confirmadme que es eso lo que queremos.
Un saludo y gracias.
