### ISSUE TITLE
Error en showerrors

### ISSUE THREAD

**Issue by tmas0** [UNIMOODLE/moodle-mod_certifygen#75]
Buenas,

Actualmente el enlace para ver los errores, en la parte administrativa, se cuelgan de un nodo incorrecto. Esto provoca que entornos con "path" en el dominio, éste se pierda. Por ejemplo http://myhost.com/mimoodle, el /mimoodle se pierde.

https://github.com/UNIMOODLE/moodle-mod_certifygen/blob/c9c1a626b6dd34faa260b7fd088e3e37a5402a9b/settings.php#L116

Creo que debería colgar de **certifygencat**.

Un saludo

**Comment by elena3ip** [comment]
que raro me parece.... entonces tampoco ves los enlaces de configuración de los subplugins?

modsettingcertifygencat es la categoría en la pagina de extensiones y certifygencat en la pagina del perfil

![image](https://github.com/user-attachments/assets/f130b4f3-6835-477a-b1ca-99c1e012421c)

**Comment by jmerinogranizo** [comment]
A mí, ya me funciona.
A expensas de lo que diga Toni.

**Comment by tmas0** [comment]
Buenas,

Comprobado que ya lo veo bien.

Un saludo
