### ISSUE TITLE
Error en showerrors al intentar visualizar la pantalla de errores

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/moodle-mod_certifygen#77]
He tenido dos errores con emisión de certificado con validación CMD y repositorio local. 
Al intentar acceder a la pantalla de errores, me salta la siguiente excepción:

![imagen](https://github.com/user-attachments/assets/20c77ea4-6fd8-4d7f-8bab-d051792ca2c0)

Error producido con la versión de la tabla certifygen sin campo modelid.

Parece que la variable $file es un boolean vacío en mi caso por lo que da un fallo al intentar conseguir el contexto.

¿Estoy haciendo algo mal?

**Comment by elena3ip** [comment]
He subido una corrección a la rama develop. Por la razón que sea, el fichero que busca no lo encuentra y no tenía controlado el error en esta pagina.

**Comment by jmerinogranizo** [comment]
Elena, con la versión del commit 0c1d65fc1273c3617aef93f578e6d9daf97a2ae7 de las 9:00 del 25/10 me sigue produciendo ese error. En la línea 161 de showerrors_table.php

**Comment by jmerinogranizo** [comment]
Me sigue ocurriendo el problema con la versión 9f63c08ceb94e2b0099a2bfa8c19ca0a3228a60a de la rama main del 20/11/2024.

**Comment by elena3ip** [comment]
Pasame el pantallazo con el error por favor para el ultimo commit del repositorio

**Comment by jmerinogranizo** [comment]
Para la versión de la rama develop:
Me sigue apareciendo este error.

![imagen](https://github.com/user-attachments/assets/a7e87bda-b177-4247-92b6-f699c07a4d5c)

El error proviene porque la variable $response['file'] y por tanto $file es un null.
   $response = $subplugin->get_file($courseid, $row->validationid);
   if (array_key_exists('file', $response)) {
          $file = $response['file'];
          $url = moodle_url::make_pluginfile_url(
                        $file->get_contextid(),
						
De las pruebas realizadas, el primer error me ha dado para una validación 'cmd' y borrando el registro correspondiente de certifygen_validations, me ha saltado el mismo error en una validación de tipo 'none'.
En los dos casos es porque dentro del método get_file del subplugin de validación, se intenta conseguir el fichero
	$file = $fs->get_file(
		$contextid,
		self::FILE_COMPONENT,
		self::FILE_AREA,
		$validationid,
		self::FILE_PATH,
		$code
	);
pero no encuentra registro en la tabla 'files' con esos parámetros.
				
Debe ser controlado por tanto que si no se encuentra el registro en esa tabla, no devuelva null y que no salte excepción al intentar conseguir $file->get_contextid.

Un saludo.

**Comment by elena3ip** [comment]
Hola, acabo de subir a develop la corrección.

**Comment by jmerinogranizo** [comment]
Perdona Elena por no contestar antes.
Ahora ya se muestra perfectamente con el listado de errores. No obstante, de la reunión del 11 de septiembre con Xavi, tengo publicado yo en mis notas: 
<ul>
<li>Xavier inicia el debate sobre cómo debe comportarse el aplicativo en caso de errores. Hay dos opciones:
<ul>
<li>Relanzar el proceso desde cero.</li>
<li>Continuar el proceso desde donde falló.</li>
</li>
</ul>
<li>Aunque Xavier es más partidario de lo primero, Juan Pablo considera que la fecha de emisión es importante sobre todo cuando la validación sí ha funcionado.</li>
<li>Se intentará por tanto dar la posibilidad de descarga manual o relanzarlo desde ese punto cuando lo que ha fallado es el almacenaje.</li>
<li>Siempre existirá la posibilidad de revocar o cancelarlo.</li>
</ul>

**Comment by elena3ip** [comment]
Genial, sobre lo que comentas de eso se encarga la tarea checkerror. Si el error de es almacenamiento lo reintenta y si falla se inicia el proceso. Si el error es de validación directamente reinincia el proceso.
