### ISSUE TITLE
Missing Usage of Capability in `access.php`

### ISSUE THREAD

**Issue by eduardokraus** [UNIMOODLE/moodle-mod_certifygen#78]
In the `access.php` file, there is the capability `mod/certifygen:addinstance`, but I couldn't find any location that uses it.

**Comment by LuksAO** [comment]
Capabilities like `mod/[modname]:addinstance` are required for all mod plugins, this is stated on [Moodle doc](https://moodledev.io/docs/4.1/apis/plugintypes/mod#accessphp---capability-defaults). It is used by Moodle's core.

**Comment by juacas** [comment]
This capability is checked by Moodle's core when creating a new activity instance. Is there any point of code where it should be checked?
This pluign use extensively the capability certifygen:manage for most of the operations and let certifygen:addinstance for Moodle to use.
IMHO it's ok as it is implemented. Please, developers, confirm.

**Comment by elena3ip** [comment]
This capability is required by Moodle.
