### ISSUE TITLE
Adjusting String Definition for Certification Validation Plugin

### ISSUE THREAD

**Issue by eduardokraus** [UNIMOODLE/moodle-mod_certifygen#79]
In the file, there is `$string['certifygenvalidationpluginname'] = $string['validationplugins'];`, and it should only have `$string['certifygenvalidationpluginname'] = 'text';`.

![Captura de Tela 2024-10-31 às 19 50 23](https://github.com/user-attachments/assets/aba74d65-673c-4bfd-8930-4e8f64d6a005)
![Captura de Tela 2024-10-31 às 19 51 44](https://github.com/user-attachments/assets/76734b18-c2af-4241-a4e9-6ce55696a5d6)

**Comment by elena3ip** [comment]
It seems that this string is not used. I'll remove it.
