### ISSUE TITLE
No se pueden crear nuevos modelos

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/moodle-mod_certifygen#87]
Con la versión de la rama develop: a603ce29fbdb7c702a66308c5680b31c0bc0cd89 del 18 de noviembre, me da un error al intentar crear un modelo.
![imagen](https://github.com/user-attachments/assets/3267e870-bcb8-4787-b536-36ade84ee5e8)
Abriendo la herramienta de desarrollo del navegador, vemos que alta excepción en la línea 9294
![imagen](https://github.com/user-attachments/assets/d460b665-df68-4c5b-9600-f6e6d1b68374)

Tal vez sea fallo mío pero podéis revisarlo o al menos indicarme que versión, puedo instalarme.

Un saludo.

**Comment by elena3ip** [comment]
Hola @tmas0  @jmerinogranizo  a mi me deja sin problema crear modelos.  ¿podeís purgar caché e intentarlo otra vez por favor?
