### ISSUE TITLE
Unnecessary use of deprecated soaplib.php

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-mod_certifygen#88]
We are using standard SoapClient:

https://github.com/UNIMOODLE/moodle-mod_certifygen/blob/6e124830565fbb87f699a4a1806bb86f5e29ee3a/validation/csv/classes/soapconnection.php#L32

end plain CURL requests:

https://github.com/UNIMOODLE/moodle-mod_certifygen/blob/6e124830565fbb87f699a4a1806bb86f5e29ee3a/validation/csv/classes/certifygenvalidation_csv.php#L97

But we are including deprecated soaplib.php https://github.com/UNIMOODLE/moodle-mod_certifygen/blob/6e124830565fbb87f699a4a1806bb86f5e29ee3a/validation/csv/classes/certifygenvalidation_csv.php#L34 aparently for nothing.

Please check and remove it to avoid:

The warning in view.php:

```
The soaplib.php file is deprecated and should not be used any more.
line 35 of /lib/soaplib.php: call to debugging()
line 34 of /mod/certifygen/validation/csv/classes/certifygenvalidation_csv.php: call to require_once()
line 217 of /lib/classes/component.php: call to include_once()
line 111 of /mod/certifygen/classes/tables/activityteacher_table.php: call to core\component::classloader()
line 164 of /mod/certifygen/classes/output/views/activity_view.php: call to mod_certifygen\tables\activityteacher_table->__construct()
line 124 of /mod/certifygen/classes/output/views/activity_view.php: call to mod_certifygen\output\views\activity_view->get_certificates_table()
line 72 of /mod/certifygen/classes/output/renderer.php: call to mod_certifygen\output\views\activity_view->export_for_template()
line 78 of /lib/classes/output/plugin_renderer_base.php: call to mod_certifygen\output\renderer->render_activity_view()
line 70 of /mod/certifygen/view.php: call to core\output\plugin_renderer_base->render()
```

**Comment by elena3ip** [comment]
Subido a develop
