### ISSUE TITLE
Enlaces rotos desde la web de administración, desde la categoría certifygen (General -> Unimoodle certifygen)

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/moodle-mod_certifygen#90]
Los enlaces desde esa categoría están rotos:

![imagen](https://github.com/user-attachments/assets/0f58391a-6dac-43cd-a6c2-49dbefda805c)

Por ejemplo, el primer enlace a la gestión de modelos va a https://XXXX.ucm.es/mod/certifygen/modelmanager.php
cuando debería ir a https://XXXX.ucm.es/moodle/mod/certifygen/modelmanager.php

Si vas directamente desde la pestaña General funcionan perfectamente.

**Comment by elena3ip** [comment]
Subido a develop la corrección.
